version: '3'

services:
  moneyzilla_app:
    container_name: moneyzilla_app
    restart: always
    env_file:
      - .env
    build: .
    command: java -jar target/app.jar
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"
    networks:
      - app_network
networks:
  app_network: